# Generated by Django 5.2 on 2025-04-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='apelido',
            new_name='nomeSocial',
        ),
        migrations.AddField(
            model_name='paciente',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telEmergencia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
