# Generated by Django 5.2 on 2025-04-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='nascimento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
