# Generated by Django 5.2 on 2025-04-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_apelido_paciente_nomesocial_paciente_celular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidade',
            name='cor',
            field=models.CharField(default='#4a90e2', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estado_civil',
            field=models.CharField(choices=[('solteiro(a)', 'Solteiro(a)'), ('casado(a)', 'Casado(a)'), ('divorciado(a)', 'Divorciado(a)'), ('viuvo(a))', 'Viúvo(a)'), ('uniao estavel', 'União estável')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Administrador'), ('secretaria', 'Secretaria'), ('recepcionista', 'Recepcionista'), ('profissional', 'Profissional'), ('paciente', 'Paciente')], max_length=20),
        ),
    ]
