# Generated by Django 5.2 on 2025-08-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_respostapergunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
