# Generated by Django 5.2 on 2025-08-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_formulario_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='consentimento_lgpd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='consentimento_marketing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='data_consentimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ip_consentimento',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='politica_privacidade_versao',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
