# Generated by Django 5.0.6 on 2025-04-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_especialidade_cor_alter_paciente_estado_civil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='complemento',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='contatoEmergencia',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='vinculo',
            field=models.CharField(choices=[('pai', 'Pai'), ('mae', 'Mãe'), ('padrasto', 'Padrasto'), ('madrasta', 'Madrasta'), ('filho_filha', 'Filho(a)'), ('irmao_irma', 'Irmão(ã)'), ('avo_avó', 'Avô(ó)'), ('neto_neta', 'Neto(a)'), ('tio_tia', 'Tio(a)'), ('primo_prima', 'Primo(a)'), ('sobrinho_sobrinha', 'Sobrinho(a)'), ('cunhado_cunhada', 'Cunhado(a)'), ('genro_nora', 'Genro/Nora'), ('sogro_sogra', 'Sogro(a)'), ('marido_esposa', 'Marido/Esposa'), ('companheiro_companheira', 'Companheiro(a)'), ('namorado_namorada', 'Namorado(a)'), ('amigo_amiga', 'Amigo(a)'), ('vizinho_vizinha', 'Vizinho(a)'), ('colega_trabalho', 'Colega de trabalho'), ('outro', 'Outro')], default=22, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cor_raca',
            field=models.CharField(choices=[('branca', 'Branca'), ('preta', 'Preta'), ('parda', 'Parda'), ('amarela', 'Amarela'), ('indígena', 'Indígena'), ('prefiro não informar', 'Prefiro não informar')], default='Não informado', max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estado_civil',
            field=models.CharField(choices=[('solteiro(a)', 'Solteiro(a)'), ('casado(a)', 'Casado(a)'), ('divorciado(a)', 'Divorciado(a)'), ('viuvo(a))', 'Viúvo(a)'), ('uniao estavel', 'União estável')], default='Não informado', max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro'), ('prefiro não informar', 'Prefiro não informar')], default='Não informado', max_length=20),
        ),
    ]
