# Generated by Django 5.2 on 2025-04-11 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_paciente_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='data_cadastro',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
