# Generated by Django 5.2 on 2025-05-01 12:00

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_paciente_complemento_paciente_contatoemergencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.caminho_foto_paciente),
        ),
    ]
