# Generated by Django 5.2 on 2025-09-22 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_paciente_consentimento_lgpd_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrequenciaMensal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes", models.PositiveIntegerField()),
                ("ano", models.PositiveIntegerField()),
                ("freq_sistema", models.PositiveIntegerField(default=0)),
                ("freq_programada", models.PositiveIntegerField(default=0)),
                ("programada_set_em", models.DateTimeField(blank=True, null=True)),
                (
                    "percentual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("primeiro_mes", "1º Mês"),
                            ("premium", "Premium"),
                            ("vip", "VIP"),
                            ("plus", "Plus"),
                            ("indefinido", "Indefinido"),
                        ],
                        default="indefinido",
                        max_length=20,
                    ),
                ),
                ("observacao", models.TextField(blank=True, null=True)),
                ("fechado", models.BooleanField(default=False)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frequencias",
                        to="core.paciente",
                    ),
                ),
                (
                    "programada_set_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="freq_programada_por",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ano", "mes"], name="core_freque_ano_5734cb_idx"
                    ),
                    models.Index(
                        fields=["paciente", "ano", "mes"],
                        name="core_freque_pacient_aeefcd_idx",
                    ),
                ],
                "unique_together": {("paciente", "mes", "ano")},
            },
        ),
        migrations.CreateModel(
            name="HistoricoStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes", models.PositiveIntegerField()),
                ("ano", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pre", "✅ Pré-Agendado"),
                            ("agendado", "✅ Agendado"),
                            ("finalizado", "✅ Consulta finalizada!"),
                            ("desistencia", "❌ D - Desmarcação"),
                            (
                                "desistencia_remarcacao",
                                "⚠️ DCR - Desmarcação com reposição",
                            ),
                            ("falta_remarcacao", "⚠️ FCR - Falta com reposição"),
                            ("falta_cobrada", "❌ FC - Falta cobrada"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "percentual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("freq_sistema", models.PositiveIntegerField(default=0)),
                ("freq_programada", models.PositiveIntegerField(default=0)),
                ("ganhou_beneficio", models.BooleanField(default=False)),
                ("data_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_status",
                        to="core.paciente",
                    ),
                ),
            ],
            options={
                "ordering": ["ano", "mes"],
                "unique_together": {("paciente", "mes", "ano")},
            },
        ),
    ]
