# Generated by Django 5.2 on 2025-04-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_paciente_data_cadastro'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Funcionario',
            new_name='Profissional',
        ),
        migrations.AddField(
            model_name='especialidade',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
