# Generated by Django 5.2 on 2025-09-26 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_frequenciamensal_historicostatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicostatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("primeiro_mes", "1º Mês"),
                    ("premium", "Premium"),
                    ("vip", "VIP"),
                    ("plus", "Plus"),
                    ("indefinido", "Indefinido"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="UsoBeneficio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes", models.PositiveIntegerField()),
                ("ano", models.PositiveIntegerField()),
                (
                    "status_no_mes",
                    models.CharField(
                        choices=[
                            ("primeiro_mes", "1º Mês"),
                            ("premium", "Premium"),
                            ("vip", "VIP"),
                            ("plus", "Plus"),
                            ("indefinido", "Indefinido"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("relaxante", "Sessão Relaxante"),
                            ("desconto", "Desconto em Pagamento"),
                            ("brinde", "Brinde"),
                            ("sessao_livre", "Sessão Livre"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "valor_desconto_aplicado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("usado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "agendamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.agendamento",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usos_beneficio",
                        to="core.paciente",
                    ),
                ),
                (
                    "usado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["paciente", "ano", "mes", "tipo"],
                        name="core_usoben_pacient_331182_idx",
                    )
                ],
                "unique_together": {("paciente", "mes", "ano", "tipo")},
            },
        ),
    ]
