# Generated by Django 5.2 on 2025-05-01 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_paciente_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='contatoEmergencia',
            new_name='nomeEmergencia',
        ),
    ]
