# Generated by Django 5.2 on 2025-05-07 15:10

import core.models
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_contatoemergencia_paciente_nomeemergencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='comissao',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='horario_trabalho',
        ),
        migrations.AddField(
            model_name='profissional',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='bairro',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='cidade',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='complemento',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='conselho1',
            field=models.CharField(choices=[('cref', 'CREF'), ('crefito', 'CREFITO'), ('cfn', 'CFN'), ('crbm', 'CRBM'), ('coren', 'COREN'), ('cra', 'CRA')], default='teste', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profissional',
            name='conselho2',
            field=models.CharField(choices=[('cref', 'CREF'), ('crefito', 'CREFITO'), ('cfn', 'CFN'), ('crbm', 'CRBM'), ('coren', 'COREN'), ('cra', 'CRA')], default='teste', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profissional',
            name='conselho3',
            field=models.CharField(choices=[('cref', 'CREF'), ('crefito', 'CREFITO'), ('cfn', 'CFN'), ('crbm', 'CRBM'), ('coren', 'COREN'), ('cra', 'CRA')], default='teste', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profissional',
            name='conselho4',
            field=models.CharField(choices=[('cref', 'CREF'), ('crefito', 'CREFITO'), ('cfn', 'CFN'), ('crbm', 'CRBM'), ('coren', 'COREN'), ('cra', 'CRA')], default='teste', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profissional',
            name='cor_raca',
            field=models.CharField(choices=[('branca', 'Branca'), ('preta', 'Preta'), ('parda', 'Parda'), ('amarela', 'Amarela'), ('indígena', 'Indígena'), ('prefiro não informar', 'Prefiro não informar')], default='Não informado', max_length=20),
        ),
        migrations.AddField(
            model_name='profissional',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='data_cadastro',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='estado',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='estado_civil',
            field=models.CharField(choices=[('solteiro(a)', 'Solteiro(a)'), ('casado(a)', 'Casado(a)'), ('divorciado(a)', 'Divorciado(a)'), ('viuvo(a))', 'Viúvo(a)'), ('uniao estavel', 'União estável')], default='Não informado', max_length=20),
        ),
        migrations.AddField(
            model_name='profissional',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.caminho_foto_profissional),
        ),
        migrations.AddField(
            model_name='profissional',
            name='naturalidade',
            field=models.CharField(default='teste', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profissional',
            name='nome',
            field=models.CharField(default=24, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profissional',
            name='nomeEmergencia',
            field=models.CharField(default=122, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profissional',
            name='nomeSocial',
            field=models.CharField(blank=True, default='Não informado', max_length=100),
        ),
        migrations.AddField(
            model_name='profissional',
            name='numero',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='numero_conselho1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profissional',
            name='numero_conselho2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profissional',
            name='numero_conselho3',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profissional',
            name='numero_conselho4',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profissional',
            name='observacao',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='rg',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='rua',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro'), ('prefiro não informar', 'Prefiro não informar')], default='Não informado', max_length=20),
        ),
        migrations.AddField(
            model_name='profissional',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='telEmergencia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='uf',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default=13.875, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profissional',
            name='vinculo',
            field=models.CharField(choices=[('pai', 'Pai'), ('mae', 'Mãe'), ('padrasto', 'Padrasto'), ('madrasta', 'Madrasta'), ('filho_filha', 'Filho(a)'), ('irmao_irma', 'Irmão(ã)'), ('avo_avó', 'Avô(ó)'), ('neto_neta', 'Neto(a)'), ('tio_tia', 'Tio(a)'), ('primo_prima', 'Primo(a)'), ('sobrinho_sobrinha', 'Sobrinho(a)'), ('cunhado_cunhada', 'Cunhado(a)'), ('genro_nora', 'Genro/Nora'), ('sogro_sogra', 'Sogro(a)'), ('marido_esposa', 'Marido/Esposa'), ('companheiro_companheira', 'Companheiro(a)'), ('namorado_namorada', 'Namorado(a)'), ('amigo_amiga', 'Amigo(a)'), ('vizinho_vizinha', 'Vizinho(a)'), ('colega_trabalho', 'Colega de trabalho'), ('outro', 'Outro')], default='pai', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nomeSocial',
            field=models.CharField(blank=True, default='Não informado', max_length=100),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
