# Generated by Django 5.2 on 2025-10-02 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_historicostatus_status_usobeneficio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_banco', models.CharField(max_length=10)),
                ('nome_banco', models.CharField(max_length=100)),
                ('agencia_banco', models.CharField(max_length=10)),
                ('conta_banco', models.CharField(max_length=20)),
                ('digito_banco', models.CharField(max_length=20)),
                ('chave_pix_banco', models.CharField(max_length=150)),
                ('tipo_conta_banco', models.CharField(choices=[('corrente', 'Corrente'), ('poupanca', 'Poupança')], max_length=20)),
                ('ativo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('contato', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('agendado', 'Agendado'), ('pago', 'Pago'), ('atrasado', 'Atrasado')], default='pendente', max_length=20)),
                ('forma_pagamento', models.CharField(blank=True, max_length=30, null=True)),
                ('documento', models.CharField(blank=True, max_length=50, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/despesas/')),
                ('recorrente', models.BooleanField(default=False)),
                ('frequencia', models.CharField(blank=True, max_length=20, null=True)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('termino', models.DateField(blank=True, null=True)),
                ('categoria', models.ForeignKey(limit_choices_to={'tipo': 'despesa'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoriafinanceira')),
                ('conta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contabancaria')),
                ('fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10)),
                ('data', models.DateTimeField()),
                ('descricao', models.CharField(max_length=255)),
                ('pessoa', models.CharField(blank=True, max_length=150, null=True)),
                ('forma_pagamento', models.CharField(max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pago', 'Pago'), ('pendente', 'Pendente')], default='pendente', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoriafinanceira')),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('agendamento_codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('atrasado', 'Atrasado')], default='pendente', max_length=20)),
                ('forma_pagamento', models.CharField(blank=True, max_length=30, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('recibo', models.FileField(blank=True, null=True, upload_to='recibos/receitas/')),
                ('categoria', models.ForeignKey(limit_choices_to={'tipo': 'receita'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoriafinanceira')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.paciente')),
            ],
        ),
    ]
