# Generated by Django 5.2 on 2025-04-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_funcionario_profissional_especialidade_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='estado_civil',
            field=models.CharField(choices=[('solteiro(a)', 'Solteiro(a)'), ('casado(a)', 'Casado(a)'), ('divoriado(a)', 'Divorciado(a)')], default='solteiro(a)', max_length=20),
        ),
    ]
