# Generated by Django 5.2 on 2025-05-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_profissional_cargo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profissional',
            old_name='numero_conselho1',
            new_name='num1_conselho',
        ),
        migrations.RenameField(
            model_name='profissional',
            old_name='numero_conselho2',
            new_name='num2_conselho',
        ),
        migrations.RenameField(
            model_name='profissional',
            old_name='numero_conselho3',
            new_name='num3_conselho',
        ),
        migrations.RenameField(
            model_name='profissional',
            old_name='numero_conselho4',
            new_name='num4_conselho',
        ),
        migrations.AddField(
            model_name='profissional',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
