# Generated by Django 5.2 on 2025-10-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_categoriadespesa_categoriafinanceira_contabancaria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fornecedor',
            old_name='cnpj',
            new_name='documento',
        ),
        migrations.RenameField(
            model_name='fornecedor',
            old_name='nome',
            new_name='nome_fantasia',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='contato',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='razao_social',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='tipo_pessoa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
