# Generated by Django 5.2 on 2025-05-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_numero_conselho1_profissional_num1_conselho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='conselho1',
            field=models.CharField(blank=True, choices=[('cref', 'CREF'), ('crefito', 'CREFITO'), ('cfn', 'CFN'), ('crbm', 'CRBM'), ('coren', 'COREN'), ('cra', 'CRA')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='conselho2',
            field=models.CharField(blank=True, choices=[('cref', 'CREF'), ('crefito', 'CREFITO'), ('cfn', 'CFN'), ('crbm', 'CRBM'), ('coren', 'COREN'), ('cra', 'CRA')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='conselho3',
            field=models.CharField(blank=True, choices=[('cref', 'CREF'), ('crefito', 'CREFITO'), ('cfn', 'CFN'), ('crbm', 'CRBM'), ('coren', 'COREN'), ('cra', 'CRA')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='conselho4',
            field=models.CharField(blank=True, choices=[('cref', 'CREF'), ('crefito', 'CREFITO'), ('cfn', 'CFN'), ('crbm', 'CRBM'), ('coren', 'COREN'), ('cra', 'CRA')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='num1_conselho',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='num2_conselho',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='num3_conselho',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='num4_conselho',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='observacao',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
