# Generated by Django 5.2 on 2025-10-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_rename_cnpj_fornecedor_documento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagamento",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("pago", "Pago"),
                    ("cancelado", "Cancelado"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pagamento",
            name="vencimento",
            field=models.DateField(blank=True, null=True),
        ),
    ]
