# Generated by Django 5.2 on 2025-10-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_pagamento_status_pagamento_vencimento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagamento",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pendente", "Pendente"),
                    ("pago", "Pago"),
                    ("cancelado", "Cancelado"),
                ],
                default="pendente",
                max_length=20,
                null=True,
            ),
        ),
    ]
