# Generated by Django 5.2 on 2025-10-14 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_pagamento_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagamento",
            name="forma_pagamento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pix", "Pix"),
                    ("credito", "Cartão de Crédito"),
                    ("debito", "Cartão de Débito"),
                    ("dinheiro", "Dinheiro"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pagamento",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("pago", "Pago"),
                    ("cancelado", "Cancelado"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
    ]
