# Generated by Django 5.2 on 2025-05-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_profissional_conselho1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='conselho1',
            field=models.CharField(blank=True, choices=[('cref', 'CREF'), ('crefito', 'CREFITO'), ('cfn', 'CFN'), ('crbm', 'CRBM'), ('coren', 'COREN'), ('cra', 'CRA')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='conselho2',
            field=models.CharField(blank=True, choices=[('cref', 'CREF'), ('crefito', 'CREFITO'), ('cfn', 'CFN'), ('crbm', 'CRBM'), ('coren', 'COREN'), ('cra', 'CRA')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='conselho3',
            field=models.CharField(blank=True, choices=[('cref', 'CREF'), ('crefito', 'CREFITO'), ('cfn', 'CFN'), ('crbm', 'CRBM'), ('coren', 'COREN'), ('cra', 'CRA')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='conselho4',
            field=models.CharField(blank=True, choices=[('cref', 'CREF'), ('crefito', 'CREFITO'), ('cfn', 'CFN'), ('crbm', 'CRBM'), ('coren', 'COREN'), ('cra', 'CRA')], max_length=20, null=True),
        ),
    ]
