# Generated by Django 5.2 on 2025-10-14 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_pagamento_forma_pagamento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagamento",
            name="receita",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pagamentos",
                to="core.receita",
            ),
        ),
    ]
