# Generated by Django 5.2 on 2025-05-09 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_profissional_conselho1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('avulso', 'Avulso'), ('pacote_5', 'Pacote com 5 sessões'), ('pacote_10', 'Pacote com 10 sessões'), ('personal', 'Personal 2x a 5x/semana'), ('mensalidade', 'Mensalidade psicoterapia')], max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('especialidades', models.ManyToManyField(to='core.especialidade')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('tipo', models.CharField(choices=[('nova', 'Nova sessão'), ('pacote', 'Nova sessão do pacote'), ('reposicao', 'Reposição DGR/FCR')], max_length=20)),
                ('recorrente', models.BooleanField(default=False)),
                ('dia_semana_recorrente', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('check', '✅ Check'), ('d', '❌ D – Desistência'), ('dcr', '⚠️ DCR – Desistência c/ remarcação'), ('fcr', '⚠️ FCR – Falta c/ remarcação'), ('fc', '❌ FC – Falta cobrada')], default='check', max_length=10)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.especialidade')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profissional')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servico')),
            ],
        ),
    ]
