# Generated by Django 5.2 on 2025-05-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_servico_agendamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='especialidades',
        ),
        migrations.AddField(
            model_name='paciente',
            name='profissao',
            field=models.CharField(default='Não informado', max_length=35),
        ),
        migrations.AddField(
            model_name='paciente',
            name='redeSocial',
            field=models.CharField(default='Não informado', max_length=35),
        ),
        migrations.DeleteModel(
            name='Agendamento',
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
    ]
