# Generated by Django 5.2 on 2025-05-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_servico_especialidades_paciente_profissao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cor_raca',
            field=models.CharField(blank=True, choices=[('branca', 'Branca'), ('preta', 'Preta'), ('parda', 'Parda'), ('amarela', 'Amarela'), ('indígena', 'Indígena'), ('prefiro não informar', 'Prefiro não informar')], default='Não informado', max_length=20, null=True),
        ),
    ]
