# Generated by Django 5.2 on 2025-10-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_paciente_nf_imposto_renda_paciente_nf_nao_aplica_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prontuario",
            old_name="exame_fisico",
            new_name="evolucao",
        ),
        migrations.AddField(
            model_name="prontuario",
            name="feedback_paciente",
            field=models.TextField(default="teste"),
            preserve_default=False,
        ),
    ]
