# Generated by Django 5.2 on 2025-10-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_exame_fisico_prontuario_evolucao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prontuario',
            name='foi_preenchido',
            field=models.BooleanField(default=False),
        ),
    ]
