# Generated by Django 5.2 on 2025-05-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='qtd_sessoes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
