# Generated by Django 5.2 on 2025-10-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_prontuario_foi_preenchido'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaofisioterapeutica',
            name='foi_preenchido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evolucao',
            name='foi_preenchido',
            field=models.BooleanField(default=False),
        ),
    ]
