# Generated by Django 5.2 on 2025-05-19 16:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_servico_qtd_sessoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='comissao_gerada',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='data_pagamento',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='obs',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='profissional',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='servico',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='forma_pagamento',
            field=models.CharField(choices=[('pix', 'Pix'), ('credito', 'Cartão de Crédito'), ('debito', 'Cartão de Débito'), ('dinheiro', 'Dinheiro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('ambiente', models.CharField(blank=True, max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pre', 'Pré-agendado'), ('agendado', 'Agendado'), ('finalizado', 'Finalizado'), ('desistencia', 'Desistência'), ('falta', 'Falta')], default='pre', max_length=20)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('especialidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.especialidade')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
                ('profissional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principal', to='core.profissional')),
                ('profissional_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auxiliar', to='core.profissional')),
                ('servico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.servico')),
            ],
        ),
        migrations.AddField(
            model_name='pagamento',
            name='agendamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.agendamento'),
        ),
        migrations.CreateModel(
            name='PacotePaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=12, unique=True)),
                ('qtd_sessoes', models.PositiveIntegerField()),
                ('valor_original', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('desconto_reais', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('desconto_percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valor_final', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('data_inicio', models.DateField(default=django.utils.timezone.now)),
                ('ativo', models.BooleanField(default=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
                ('profissional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profissional')),
                ('servico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.servico')),
            ],
        ),
        migrations.AddField(
            model_name='agendamento',
            name='pacote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pacotepaciente'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='pacote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pacotepaciente'),
        ),
    ]
