# Generated by Django 5.2 on 2025-10-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_avaliacaofisioterapeutica_foi_preenchido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolucao',
            name='ajustes_plano',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='amplitude_atual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='amplitude_inicio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='amplitude_observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='avds_atual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='avds_inicio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='avds_observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='condutas_mantidas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='condutas_tecnicas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='consciencia_expectativa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='consciencia_realidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='dor_expectativa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='dor_observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='dor_realidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='edema_atual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='edema_inicio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='edema_observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='emocao_expectativa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='emocao_realidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='emocionais_atual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='emocionais_inicio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='emocionais_observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='energia_expectativa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='energia_realidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='explicacao_continuidade',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='forca_atual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='forca_inicio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='forca_observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='intercorrencias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='mensagem_paciente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='mobilidade_expectativa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='mobilidade_realidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='objetivos_ciclo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='observacoes_internas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='orientacoes_grupo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='outro_complementar_texto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='postura_atual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='postura_inicio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='postura_observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='processo_terapeutico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='queixa_principal_inicial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='reacoes_paciente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='resposta_paciente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='sintese_evolucao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
