# Generated by Django 5.2 on 2025-05-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_pagamento_comissao_gerada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacotepaciente',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=8),
            preserve_default=False,
        ),
    ]
