# Generated by Django 5.2 on 2025-10-31 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_evolucao_ajustes_plano_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaofisioterapeutica',
            name='agendamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.agendamento'),
        ),
    ]
