# Generated by Django 5.2 on 2025-11-01 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_avaliacaofisioterapeutica_agendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaofisioterapeutica',
            name='usuario_logado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avaliacaofisioterapeutica',
            name='horas_sono',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
