# Generated by Django 5.2 on 2025-05-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_pacotepaciente_valor_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='profissional',
            new_name='profissional_1',
        ),
    ]
