# Generated by Django 5.2 on 2025-11-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_avaliacaofisioterapeutica_usuario_logado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaofisioterapeutica',
            name='horas_sono',
            field=models.TextField(blank=True, default=0, null=True),
        ),
    ]
