# Generated by Django 5.2 on 2025-05-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_rename_profissional_agendamento_profissional_1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendamento",
            name="status",
            field=models.CharField(
                choices=[
                    ("pre", "✅ Pré-Agendado"),
                    ("agendado", "✅ Agendado"),
                    ("finalizado", "✅ Consulta finalizada!"),
                    ("desmarcacao", "❌ D - Desmarcação"),
                    ("dcr", "⚠ DCR: Desmarcação com Reposição"),
                    ("fcr", "⚠ FCR: Falta com Reposição"),
                    ("falta_cobrada", "❌ FC: Falta Cobrada"),
                ],
                default="pre",
                max_length=20,
            ),
        ),
    ]
