# Generated by Django 5.2 on 2025-05-22 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_agendamento_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagamento",
            name="observacoes",
        ),
    ]
