# Generated by Django 5.2 on 2025-11-01 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_avaliacaofisioterapeutica_horas_sono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacaofisioterapeutica',
            old_name='usuario_logado',
            new_name='criado_por',
        ),
    ]
