# Generated by Django 5.2 on 2025-11-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_usuario_logado_avaliacaofisioterapeutica_criado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaofisioterapeutica',
            name='nao_se_aplica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evolucao',
            name='nao_se_aplica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prontuario',
            name='nao_se_aplica',
            field=models.BooleanField(default=False),
        ),
    ]
