# Generated by Django 5.2 on 2025-05-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_remove_pagamento_observacoes"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="hora_fim_aux",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="hora_inicio_aux",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="status",
            field=models.CharField(
                choices=[
                    ("pre", "✅ Pré-Agendado"),
                    ("agendado", "✅ Agendado"),
                    ("finalizado", "✅ Consulta finalizada!"),
                    ("desistencia", "❌ D - Desmarcação"),
                    ("desistencia_remarcacao", "⚠️ DCR - Desmarcação com reposição"),
                    ("falta_remarcacao", "⚠️ FCR - Falta com reposição"),
                    ("falta_cobrada", "❌ FC - Falta cobrada"),
                ],
                default="pre",
                max_length=30,
            ),
        ),
    ]
