# Generated by Django 5.2 on 2025-05-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_agendamento_hora_fim_aux_agendamento_hora_inicio_aux_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pacotepaciente",
            name="codigo_reposicao",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
