# Generated by Django 5.2 on 2025-11-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_avaliacaofisioterapeutica_nao_se_aplica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaofisioterapeutica',
            name='receptividade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
