# Generated by Django 5.2 on 2025-11-04 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_avaliacaofisioterapeutica_receptividade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaofisioterapeutica',
            name='agendamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.agendamento'),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='agendamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.agendamento'),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='agendamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.agendamento'),
        ),
    ]
