# Generated by Django 5.2 on 2025-05-30 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_pacotepaciente_codigo_reposicao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pacotepaciente",
            name="codigo_reposicao",
        ),
    ]
