# Generated by Django 5.2 on 2025-05-30 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_remove_pacotepaciente_codigo_reposicao"),
    ]

    operations = [
        migrations.AddField(
            model_name="pacotepaciente",
            name="tipo_reposicao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("d", "Reposição D"),
                    ("dcr", "Reposição DCR"),
                    ("fcr", "Reposição FCR"),
                ],
                help_text="Tipo de reposição, se for um pacote de reposição",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="servico",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.servico",
            ),
        ),
    ]
