# Generated by Django 5.2 on 2025-11-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_alter_avaliacaofisioterapeutica_agendamento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="avaliacaofisioterapeutica",
            name="mobilidade_forca_items",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
