# Generated by Django 5.2 on 2025-05-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_pacotepaciente_tipo_reposicao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pacotepaciente",
            name="valor_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
