# Generated by Django 5.2 on 2025-11-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_avaliacaofisioterapeutica_mobilidade_forca_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacaofisioterapeutica',
            name='mobilidade_forca_items',
        ),
        migrations.AddField(
            model_name='avaliacaofisioterapeutica',
            name='forca_dor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='avaliacaofisioterapeutica',
            name='forca_grau',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='avaliacaofisioterapeutica',
            name='forca_grupo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='avaliacaofisioterapeutica',
            name='mobilidade_ativa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='avaliacaofisioterapeutica',
            name='mobilidade_dor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='avaliacaofisioterapeutica',
            name='mobilidade_passiva',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='avaliacaofisioterapeutica',
            name='mobilidade_regiao',
            field=models.TextField(blank=True),
        ),
    ]
