# Generated by Django 5.2 on 2025-05-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_pacotepaciente_valor_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pacotepaciente",
            name="valor_total",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
