# Generated by Django 5.0.6 on 2025-12-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_avaliacaofisioterapeutica_mobilidade_forca_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaContasReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=False)),
            ],
        ),
    ]
