# Generated by Django 5.2 on 2025-05-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_alter_pacotepaciente_valor_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="foi_reposto",
            field=models.BooleanField(default=False),
        ),
    ]
