# Generated by Django 5.0.6 on 2025-12-03 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_categoriacontasreceber'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoria de Conta',
                'verbose_name_plural': 'Categorias de Conta',
                'ordering': ['tipo', 'ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='GrupoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código do grupo (ex: 1, 2, 3)', max_length=10)),
                ('descricao', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='core.categoriaconta')),
            ],
            options={
                'verbose_name': 'Grupo de Conta',
                'verbose_name_plural': 'Grupos de Conta',
                'ordering': ['categoria', 'ordem', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='SubgrupoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código do subgrupo (ex: 1, 2, 3)', max_length=10)),
                ('descricao', models.CharField(max_length=200)),
                ('codigo_completo', models.CharField(editable=False, max_length=20, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
                ('permite_lancamento_direto', models.BooleanField(default=True)),
                ('eh_centro_custo', models.BooleanField(default=False, help_text='Se é um centro de custo específico')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_criadas', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgrupos', to='core.grupoconta')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'ordering': ['grupo__categoria', 'grupo__ordem', 'ordem', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='LancamentoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimento', models.CharField(choices=[('C', 'Crédito'), ('D', 'Débito')], max_length=1)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_lancamento', models.DateField()),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado'), ('atrasado', 'Atrasado')], default='pendente', max_length=20)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('pix', 'Pix'), ('credito', 'Cartão de Crédito'), ('debito', 'Cartão de Débito'), ('dinheiro', 'Dinheiro'), ('transferencia', 'Transferência'), ('boleto', 'Boleto'), ('outro', 'Outro')], max_length=30, null=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/lancamentos/')),
                ('observacoes', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('agendamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.agendamento')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.paciente')),
                ('pacote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pacotepaciente')),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profissional')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='core.subgrupoconta')),
            ],
            options={
                'verbose_name': 'Lançamento Contábil',
                'verbose_name_plural': 'Lançamentos Contábeis',
                'ordering': ['-data_lancamento', '-data_criacao'],
            },
        ),
        migrations.AddConstraint(
            model_name='grupoconta',
            constraint=models.UniqueConstraint(fields=('categoria', 'codigo'), name='unique_grupo_por_categoria'),
        ),
        migrations.AddConstraint(
            model_name='subgrupoconta',
            constraint=models.UniqueConstraint(fields=('grupo', 'codigo'), name='unique_conta_por_grupo'),
        ),
        migrations.AddIndex(
            model_name='lancamentoconta',
            index=models.Index(fields=['conta', 'data_lancamento'], name='core_lancam_conta_i_5776af_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamentoconta',
            index=models.Index(fields=['status', 'data_vencimento'], name='core_lancam_status_32216f_idx'),
        ),
    ]
