# Generated by Django 5.2 on 2025-05-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_agendamento_foi_reposto"),
    ]

    operations = [
        migrations.AddField(
            model_name="pacotepaciente",
            name="eh_reposicao",
            field=models.BooleanField(default=False),
        ),
    ]
