# Generated by Django 5.0.6 on 2025-12-05 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_categoriaconta_grupoconta_subgrupoconta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='conta_contabil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos', to='core.subgrupoconta', verbose_name='Conta Contábil'),
        ),
    ]
