# Generated by Django 5.2 on 2025-05-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_pacotepaciente_eh_reposicao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pacotepaciente",
            name="valor_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
