# Generated by Django 5.0.6 on 2025-12-08 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_servico_conta_contabil'),
    ]

    operations = [
        migrations.AddField(
            model_name='contabancaria',
            name='conta_contabil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conta_bancaria', to='core.subgrupoconta', verbose_name='Conta Contábil'),
        ),
    ]
