# Generated by Django 5.0.6 on 2025-06-19 14:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_pacotepaciente_valor_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('pre', '✅ Pré-Agendado'), ('agendado', '✅ Agendado'), ('finalizado', '✅ Consulta finalizada!'), ('desistencia', '❌ D - Desmarcação'), ('desistencia_remarcacao', '⚠️ DCR - Desmarcação com reposição'), ('falta_remarcacao', '⚠️ FCR - Falta com reposição'), ('falta_cobrada', '❌ FC - Falta cobrada')], default='agendado', max_length=30),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
