# Generated by Django 5.2 on 2025-06-23 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_alter_agendamento_status_alter_pagamento_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="observacao_autor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="observacao_data",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
