# Generated by Django 5.0.6 on 2025-12-09 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_contabancaria_conta_contabil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriacontasreceber',
            name='conta_contabil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoria_conta_receber', to='core.subgrupoconta', verbose_name='Conta Contábil'),
        ),
    ]
