# Generated by Django 5.2 on 2025-06-23 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_agendamento_observacao_autor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendamento",
            name="observacao_autor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="observacoes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
