# Generated by Django 5.0.6 on 2025-12-13 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_categoriacontasreceber_conta_contabil'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='categoria_receita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoriacontasreceber', verbose_name='Categoria da Receita'),
        ),
        migrations.AddField(
            model_name='receita',
            name='data_recebimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
