# Generated by Django 5.2 on 2025-06-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_agendamento_observacao_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='valor_hora',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
