# Generated by Django 5.2 on 2025-12-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_receita_categoria_receita_receita_data_recebimento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagamento",
            name="vencimento",
        ),
        migrations.AddField(
            model_name="pagamento",
            name="observacoes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
