# Generated by Django 5.2 on 2025-12-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_remove_pagamento_vencimento_pagamento_observacoes"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagamento",
            name="vencimento",
            field=models.DateField(blank=True, null=True),
        ),
    ]
