# Generated by Django 5.0.6 on 2025-07-08 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_profissional_valor_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Administrador'), ('secretaria', 'Secretaria'), ('recepcionista', 'Recepcionista'), ('profissional', 'Profissional'), ('gerente', 'Gerente'), ('financeiro', 'Financeiro'), ('coordenador', 'Coordenador Clínico'), ('supervisor', 'Supervisor'), ('estagiario', 'Estagiário'), ('suporte', 'Suporte Técnico')], max_length=20),
        ),
        migrations.CreateModel(
            name='LogAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('objeto_id', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
