# Generated by Django 5.2 on 2025-12-14 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_pagamento_vencimento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagamento",
            name="observacoes",
        ),
    ]
