# Generated by Django 5.0.6 on 2025-08-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_paciente_conferido_paciente_pre_cadastro_pendencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='redeSocial',
            field=models.CharField(default='Não informado', max_length=35),
        ),
    ]
