# Generated by Django 5.2 on 2025-12-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_remove_pagamento_observacoes"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagamento",
            name="observacoes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
