# Generated by Django 5.2 on 2025-12-19 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_pagamento_observacoes"),
    ]

    operations = [
        migrations.CreateModel(
            name="VinculoFamiliar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("pai", "Pai"),
                            ("mae", "Mãe"),
                            ("responsavel_legal", "Responsável legal"),
                            ("avo", "Avô/Avó"),
                            ("tio", "Tio/Tia"),
                            ("irmao", "Irmão/Irmã"),
                            ("conjuge", "Cônjuge"),
                            ("outro", "Outro"),
                        ],
                        max_length=30,
                    ),
                ),
                ("responsavel_legal", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "familiar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="familiares",
                        to="core.paciente",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculos",
                        to="core.paciente",
                    ),
                ),
            ],
        ),
    ]
