# Generated by Django 5.0.6 on 2025-12-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_vinculofamiliar'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='consentimento_tratamento',
            field=models.BooleanField(default=False),
        ),
    ]
