# Generated by Django 5.0.6 on 2025-12-22 16:12

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_paciente_consentimento_tratamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=50)),
                ('arquivo', models.FileField(upload_to=core.models.caminho_documento_profissional)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.profissional')),
            ],
        ),
    ]
