# Generated by Django 5.2 on 2025-12-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_documentoprofissional"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentoClinica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="documentoprofissional",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("comprovante_conselho", "Comprovante de Pagamento Conselho"),
                    ("diploma", "Diploma"),
                    ("carteira_conselho", "Carteira do conselho"),
                ],
                max_length=50,
            ),
        ),
    ]
