# Generated by Django 5.0.6 on 2025-12-23 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_documentoclinica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='pacote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receitas', to='core.pacotepaciente'),
        ),
    ]
