# Generated by Django 5.0.6 on 2025-12-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_receita_pacote'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='receita',
            constraint=models.UniqueConstraint(condition=models.Q(('pacote__isnull', False)), fields=('pacote',), name='unique_receita_por_pacote'),
        ),
    ]
