# Generated by Django 5.0.6 on 2026-01-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_receita_unique_receita_por_pacote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidadeReposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reposicao', models.CharField(choices=[('d', 'Reposição D'), ('dcr', 'Reposição DCR'), ('fcr', 'Reposição FCR')], max_length=10, unique=True)),
                ('dias_validade', models.PositiveIntegerField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Validade de Reposição',
                'verbose_name_plural': 'Validades de Reposição',
                'ordering': ['tipo_reposicao'],
            },
        ),
    ]
