# Generated by Django 5.2 on 2026-01-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_validadereposicao"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="data_desmarcacao",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
