# Generated by Django 5.0.6 on 2026-01-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_agendamento_data_desmarcacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_abertura', models.TimeField()),
                ('horario_fechamento', models.TimeField()),
                ('dias_funcionamento', models.JSONField(default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
