# Generated by Django 5.2 on 2026-01-07 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_configagenda"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="bloqueado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pacientes_bloqueados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="bloqueio_beneficios",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paciente",
            name="bloqueio_descontos",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paciente",
            name="bloqueio_premios",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paciente",
            name="data_bloqueio",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paciente",
            name="motivo_bloqueio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="paciente",
            name="ultimo_beneficio_aniversario",
            field=models.DateField(blank=True, null=True),
        ),
    ]
