# Generated by Django 5.0.6 on 2026-01-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_paciente_bloqueado_por_paciente_bloqueio_beneficios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidadeBeneficios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_beneficio', models.CharField(choices=[('beneficio', 'Benefício Mensal (VIP/Premium)'), ('aniversario', 'Benefício de Aniversário')], max_length=20, unique=True)),
                ('dias_validade', models.PositiveIntegerField(help_text='Número de dias de validade após concessão')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Validade de Benefício',
                'verbose_name_plural': 'Validades de Benefícios',
                'ordering': ['tipo_beneficio'],
            },
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='bloqueado_por',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='bloqueio_beneficios',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='bloqueio_descontos',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='bloqueio_premios',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='data_bloqueio',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='motivo_bloqueio',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='ultimo_beneficio_aniversario',
        ),
    ]
