# Generated by Django 5.2 on 2026-01-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_validadebeneficios_remove_paciente_bloqueado_por_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usobeneficio",
            name="valido_ate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
