# Generated by Django 5.0.6 on 2026-01-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_usobeneficio_valido_ate'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='uso_sistema',
            field=models.BooleanField(default=False),
        ),
    ]
