# Generated by Django 5.0.6 on 2026-01-16 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_servico_uso_sistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('pre', 'Pré-Agendado'), ('agendado', 'Agendado'), ('finalizado', 'Consulta finalizada!'), ('desistencia', 'D - Desmarcação'), ('desistencia_remarcacao', 'DCR - Desmarcação com reposição'), ('falta_remarcacao', 'FCR - Falta com reposição'), ('falta_cobrada', 'FC - Falta cobrada')], default='agendado', max_length=30),
        ),
        migrations.CreateModel(
            name='EscalaBaseProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('seg', 'Segunda'), ('ter', 'Terça'), ('qua', 'Quarta'), ('qui', 'Quinta'), ('sex', 'Sexta'), ('sab', 'Sábado'), ('dom', 'Domingo')], max_length=3)),
                ('ativo', models.BooleanField(default=False)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fim', models.TimeField(blank=True, null=True)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escala_base', to='core.profissional')),
            ],
            options={
                'unique_together': {('profissional', 'dia_semana')},
            },
        ),
    ]
