# Generated by Django 5.2 on 2026-01-19 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_alter_agendamento_status_escalabaseprofissional"),
    ]

    operations = [
        migrations.CreateModel(
            name="MensagemPadrao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("mensagem", models.TextField(blank=True)),
                ("criado_em", models.DateField(auto_now_add=True)),
                ("ativo", models.BooleanField(default=False)),
            ],
        ),
    ]
