# Generated by Django 5.0.6 on 2026-01-20 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_mensagempadrao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lembrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('agendamento', 'Agendamento'), ('pagamento', 'Pagamento'), ('cadastro', 'Cadastro'), ('nf', 'Nota Fiscal'), ('manual', 'Manual')], max_length=30)),
                ('data_disparo', models.DateTimeField()),
                ('titulo', models.CharField(max_length=100)),
                ('mensagem', models.TextField()),
                ('disparado', models.BooleanField(default=False)),
                ('origem', models.CharField(blank=True, help_text='Ex: nf_pendente, pacote_finalizado, pagamento', max_length=50, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('agendamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.agendamento')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.paciente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lembretes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotaFiscalPendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('competencia', models.DateField(help_text='Mês/Ano fiscal da NF')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('emitida', 'Emitida')], default='pendente', max_length=20)),
                ('previsao_emissao', models.DateField(blank=True, null=True)),
                ('emitida_em', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.receita')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('mensagem', models.TextField()),
                ('tipo', models.CharField(choices=[('info', 'Informação'), ('alerta', 'Alerta'), ('sucesso', 'Sucesso'), ('erro', 'Erro'), ('lembrete', 'Lembrete')], default='info', max_length=20)),
                ('lida', models.BooleanField(default=False)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('agendamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.agendamento')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.paciente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
