# Generated by Django 5.2 on 2026-01-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_lembrete_notafiscalpendente_notificacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenAcessoPublico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255, unique=True)),
                ("finalidade", models.CharField(max_length=100)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("expira_em", models.DateTimeField()),
                ("usado_em", models.DateTimeField(blank=True, null=True)),
                ("ip_uso", models.GenericIPAddressField(blank=True, null=True)),
                ("ativo", models.BooleanField(default=True)),
            ],
        ),
    ]
