# Generated by Django 5.0.6 on 2026-01-26 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_tokenacessopublico'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscalEmitida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('data_emissao', models.DateField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('pendencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emissoes', to='core.notafiscalpendente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_emissao'],
            },
        ),
    ]
