# Generated by Django 5.2 on 2026-01-29 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_notafiscalemitida"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notafiscalemitida",
            name="pendencia",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emissoes",
                to="core.notafiscalpendente",
            ),
        ),
        migrations.AlterField(
            model_name="notafiscalpendente",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("emitida", "Emitida"),
                    ("cancelada", "Cancelada"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
    ]
