# Generated by Django 5.2 on 2026-01-30 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_alter_notafiscalemitida_pendencia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notafiscalemitida",
            name="pendencia",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nota_emitida",
                to="core.notafiscalpendente",
            ),
        ),
        migrations.AlterField(
            model_name="notafiscalpendente",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("emitida", "Emitida"),
                    ("atrasado", "Atrasado"),
                    ("cancelada", "Cancelada"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="NotaFiscalCancelada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "motivo_cancelamento",
                    models.CharField(
                        choices=[
                            ("p_desconto", "Pagamento com desconto"),
                            ("p_nao_quis", "Paciente não quis"),
                            ("outro", "Outro"),
                        ],
                        max_length=30,
                    ),
                ),
                ("observacao", models.TextField(blank=True, null=True)),
                ("data_cancelamento", models.DateTimeField(auto_now_add=True)),
                (
                    "pendencia",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancelamento",
                        to="core.notafiscalpendente",
                    ),
                ),
            ],
        ),
    ]
