# Generated by Django 5.2 on 2026-02-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_alter_notafiscalemitida_pendencia_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoDocumentoEmpresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_documento", models.CharField(max_length=100)),
                ("validade", models.CharField(max_length=20)),
                ("ativo", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="status",
            field=models.CharField(
                choices=[
                    ("pre", "Pré-Agendado"),
                    ("agendado", "Agendado"),
                    ("finalizado", "Consulta finalizada!"),
                    ("desistencia_remarcacao", "DCR - Desmarcação com reposição"),
                    ("falta_remarcacao", "FCR - Falta com reposição"),
                    ("falta_cobrada", "FC - Falta cobrada"),
                    ("desistencia", "D - Desistência"),
                ],
                default="agendado",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="receita",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("pago", "Pago"),
                    ("atrasado", "Atrasado"),
                    ("cancelada", "Cancelada"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
    ]
