# Generated by Django 5.0.6 on 2026-02-02 16:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_tipodocumentoempresa_alter_agendamento_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoclinica',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/clinica/'),
        ),
        migrations.AddField(
            model_name='documentoclinica',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='documentoclinica',
            name='nome',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='documentoclinica',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentoclinica',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='documentoclinica',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='core.tipodocumentoempresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentoclinica',
            name='validade',
            field=models.DateField(blank=True, null=True),
        ),
    ]
