# Generated by Django 5.0.6 on 2026-02-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_documentoclinica_arquivo_documentoclinica_criado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoclinica',
            name='arquivo',
            field=models.FileField(upload_to='documentos/clinica/'),
        ),
        migrations.AlterField(
            model_name='documentoclinica',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='documentoclinica',
            name='nome',
            field=models.CharField(editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='documentoclinica',
            name='observacao',
            field=models.TextField(),
        ),
    ]
