# Generated by Django 5.0.6 on 2026-02-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_alter_documentoclinica_arquivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipodocumentoempresa',
            name='validade',
        ),
        migrations.AddField(
            model_name='tipodocumentoempresa',
            name='exige_validade',
            field=models.BooleanField(default=False),
        ),
    ]
