# Generated by Django 5.2 on 2026-02-07 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_lembreteagenda"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lembreteagenda",
            name="agendamento",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lembrete_agenda",
                to="core.agendamento",
            ),
        ),
    ]
