# Generated by Django 5.0.6 on 2026-02-12 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_alter_lembreteagenda_agendamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutividadeMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado')], default='aberto', max_length=10)),
                ('total_previstas_min', models.IntegerField(default=0)),
                ('total_trabalhadas_min', models.IntegerField(default=0)),
                ('total_saldo_min', models.IntegerField(default=0)),
                ('total_individual_min', models.IntegerField(default=0)),
                ('total_conjunto_min', models.IntegerField(default=0)),
                ('total_prontuario_min', models.IntegerField(default=0)),
                ('total_coord_min', models.IntegerField(default=0)),
                ('total_buro_min', models.IntegerField(default=0)),
                ('total_avaliacoes', models.IntegerField(default=0)),
                ('total_evolucoes', models.IntegerField(default=0)),
                ('total_prontuarios_qtd', models.IntegerField(default=0)),
                ('perc_horas_trabalhadas', models.IntegerField(default=0)),
                ('perc_saldo', models.IntegerField(default=0)),
                ('razao_prontuario', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('profissional', 'ano', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='ProdutividadeDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField()),
                ('tipo_dia', models.CharField(max_length=20)),
                ('presenca', models.CharField(max_length=20)),
                ('horas_previstas_min', models.IntegerField(default=0)),
                ('horas_prontuario_min', models.IntegerField(default=0)),
                ('horas_coord_min', models.IntegerField(default=0)),
                ('horas_buro_min', models.IntegerField(default=0)),
                ('individual_min', models.IntegerField(default=0)),
                ('conjunto_min', models.IntegerField(default=0)),
                ('avaliacoes_qtd', models.IntegerField(default=0)),
                ('evolucoes_qtd', models.IntegerField(default=0)),
                ('prontuarios_qtd', models.IntegerField(default=0)),
                ('total_trabalhado_min', models.IntegerField(default=0)),
                ('saldo_min', models.IntegerField(default=0)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='core.produtividademensal')),
            ],
            options={
                'unique_together': {('relatorio', 'dia')},
            },
        ),
    ]
