# Generated by Django 5.0.6 on 2026-02-12 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_produtividademensal_produtividadedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtividademensal',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profissional'),
        ),
    ]
