# Generated by Django 5.0.6 on 2026-02-13 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_alter_produtividademensal_profissional'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoEscalaProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='core.escalabaseprofissional')),
            ],
            options={
                'ordering': ['hora_inicio'],
            },
        ),
    ]
