# Generated by Django 5.0.6 on 2026-02-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_turnoescalaprofissional'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
